openapi: 3.0.0
info:
  contact:
    email: snowmerak@outlook.com
    name: snowmerak
  description: The ggeco API Documentation
  title: ggeco
  version: 1.1.0
paths:
  /app/auth/refresh:
    post:
      description: Refresh Access Token
      parameters:
      - in: header
        name: Authorization
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppRefreshResponse'
          description: OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: Bad Request
        "500":
          content:
            text/plain:
              schema:
                type: string
          description: Internal Server Error
      summary: Refresh Access Token
  /app/auth/signin:
    post:
      description: Sign in with OAuth2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppSignInRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppSignInResponse'
          description: OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: Bad Request
        "500":
          content:
            text/plain:
              schema:
                type: string
          description: Internal Server Error
      summary: Sign in with OAuth2
components:
  schemas:
    AppRefreshResponse:
      properties:
        access_token:
          type: string
      type: object
    AppSignInRequest:
      properties:
        access_token:
          type: string
        kakao_account:
          type: boolean
        naver_account:
          type: boolean
      required:
      - access_token
      type: object
    AppSignInResponse:
      properties:
        refresh_token:
          type: string
      type: object
